fieldLayouts:
  a0b274ef-3b6f-403a-b892-7bc9e80e6f2f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 6d85b18f-e87f-48bb-a61a-e8f66634cb21
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 37881f0a-f631-4347-9f74-535d972c9c68
        userCondition: null
handle: jobProgrammingLanguages
name: 'Job Programming Languages'
