color: null
fieldLayouts:
  b2c677aa-270a-4525-ac75-ab812873a9ef:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 54ceaa7a-f66f-4e3e-8da0-7f8487ac4cc2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a891b39d-03a3-45e3-b276-17186acb4746 # Simple One-Line Text Field
            handle: subline
            includeInCards: false
            instructions: null
            label: Subline
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b1e586d3-bb59-4815-b952-a7b20f518554
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fa292818-e2be-4621-a3fe-fa84e94dffd3 # Simple WYSIWYG Content
            handle: description
            includeInCards: false
            instructions: null
            label: Description
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5c4983fd-f41f-464d-8ba7-4e0a4a3e5844
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c8176449-1246-4efc-9b42-8e70f5b84306 # Job Benefit Categories
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 458088e4-9f47-4e90-a38e-ffc7ebdbf968
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f9d16bf2-5cd7-49fc-89d5-6f3a67c0e75b # Job Programming Languages
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 11fc87ae-7df9-45df-8346-31f77920282b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9b0e5a91-7470-4931-8137-bf361cd4b2e2 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 567a675d-edd6-4b68-8e07-ab7502571627
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7fe80068-e4ec-4c89-b177-a20404e9c247
        userCondition: null
handle: job
hasTitleField: true
icon: ''
name: Job
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
