defaultPlacement: end
fieldLayouts:
  9fc06d5b-a84b-4a52-aaff-72e969000558:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 30c2901d-ba9c-4108-9be3-ac6dad180763
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 65f42813-b1a9-4f17-bc3a-2d329422c5e4 # Simple Multi-Line Text Field
            handle: description
            includeInCards: false
            instructions: null
            label: Description
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef49b420-b96b-4795-a04f-9a919398c7f4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 08b2f1d0-b0f9-40e1-be2a-9837eeb82a82
        userCondition: null
handle: jobBenefitCategories
name: 'Job Benefit Categories'
siteSettings:
  b342a358-6ba6-41a2-b520-3bb922b51bde: # Testsite
    hasUrls: true
    template: null
    uriFormat: 'job-category/{slug}'
structure:
  maxLevels: 1
  uid: a637430c-3835-4224-a061-6bac0abed042
